
[[language]]
name = "cil"
scope = "source.cil"
injection-regex = "cil"
file-types = ["il", "cil", "msil"]
comment-tokens = "//"
block-comment-tokens = { start = "/*", end = "*/" }

[[grammar]]
name = "cil"
source = { git = "https://github.com/AFatNiBBa/tree-sitter-cil", rev = "ba13685a50ab50f1724aaa53e503b6736885e381" }